export const PROJECT = [
  {
    id: 1,
    name: "TodayTrip",
    date: "2024.01.20 - 2024.02.26",
    images: [
      ["/images/HTML.svg", "HTML"],
      ["/images/TypeScript.svg", "TypeScript"],
      ["/images/NextJS-Dark.svg", "NextJS-Dark"],
    ],
    skills: " Next.js, TypeScript, React-Query, Google Maps API, CSS Modules",
    github: "https://github.com/CodeJaws/Jawstify",
    deployment: "https://taskify4.vercel.app",
    description: " 개인 및 팀 일정을 함께 관리할 수 있는 반응형 칸반보드 플랫폼",
    accomplishment: [
      "팀 회의 주도 및 의견 조율해 방향성 설명, 팀 멘토와의 소통 및 발표 담당",
      "대시보드/사이드바/초대 페이지 개발 및 무한 스크롤 구현",
      "API 문제 대응 및  다른 팀에게 해결 방안 공유",
      "대표 이미지 셀렉 및 이미지 기반으로 홈 화면 이미지 수정",
      "리팩토링을 통해 React-query 기반 상태 관리로 컴포넌트 간 데이터 연동 문제 해결",
      "전체적인 QA 담당",
    ],
  },
  {
    id: 2,
    name: "Jawstify",
    date: "2023.12.18 ~ 2024.01.05",
    images: [
      ["/images/HTML.svg", "HTML"],
      ["/images/TypeScript.svg", "TypeScript"],
      ["/images/NextJS-Dark.svg", "NextJS-Dark"],
    ],
    skills: "Next.js, React-query, TypeScript, Zustand,Styled-components",
    github: "https://github.com/CodeJaws/Jawstify",
    deployment: "https://taskify4.vercel.app",
    description: " 개인 및 팀 일정을 함께 관리할 수 있는 반응형 칸반보드 플랫폼",
    accomplishment: [
      "팀 회의 주도 및 의견 조율해 방향성 설명, 팀 멘토와의 소통 및 발표 담당",
      "대시보드/사이드바/초대 페이지 개발 및 무한 스크롤 구현",
      "API 문제 대응 및  다른 팀에게 해결 방안 공유",
      "대표 이미지 셀렉 및 이미지 기반으로 홈 화면 이미지 수정",
      "리팩토링을 통해 React-query 기반 상태 관리로 컴포넌트 간 데이터 연동 문제 해결",
      "전체적인 QA 담당",
    ],
  },
  {
    id: 3,
    name: "OpenMind",
    date: " 2023.12.18 ~ 2024.01.05",
    images: [
      ["/images/HTML.svg", "HTML"],
      ["/images/TypeScript.svg", "TypeScript"],
      ["/images/NextJS-Dark.svg", "NextJS-Dark"],
    ],
    skills: "Next.js, React-query, TypeScript, Zustand,Styled-components",
    github: "https://github.com/CodeJaws/Jawstify",
    deployment: "https://taskify4.vercel.app",
    description: " 개인 및 팀 일정을 함께 관리할 수 있는 반응형 칸반보드 플랫폼",
    accomplishment: [
      "팀 회의 주도 및 의견 조율해 방향성 설명, 팀 멘토와의 소통 및 발표 담당",
      "대시보드/사이드바/초대 페이지 개발 및 무한 스크롤 구현",
      "API 문제 대응 및  다른 팀에게 해결 방안 공유",
      "대표 이미지 셀렉 및 이미지 기반으로 홈 화면 이미지 수정",
      "리팩토링을 통해 React-query 기반 상태 관리로 컴포넌트 간 데이터 연동 문제 해결",
      "전체적인 QA 담당",
    ],
  },
  {
    id: 4,
    name: "번역방",
    date: " 2023.12.18 ~ 2024.01.05",
    images: [
      ["/images/HTML.svg", "HTML"],
      ["/images/TypeScript.svg", "TypeScript"],
      ["/images/NextJS-Dark.svg", "NextJS-Dark"],
    ],
    skills: "Next.js, React-query, TypeScript, Zustand,Styled-components",
    github: "https://github.com/CodeJaws/Jawstify",
    deployment: "https://taskify4.vercel.app",
    description: " 개인 및 팀 일정을 함께 관리할 수 있는 반응형 칸반보드 플랫폼",
    accomplishment: [
      "팀 회의 주도 및 의견 조율해 방향성 설명, 팀 멘토와의 소통 및 발표 담당",
      "대시보드/사이드바/초대 페이지 개발 및 무한 스크롤 구현",
      "API 문제 대응 및  다른 팀에게 해결 방안 공유",
      "대표 이미지 셀렉 및 이미지 기반으로 홈 화면 이미지 수정",
      "리팩토링을 통해 React-query 기반 상태 관리로 컴포넌트 간 데이터 연동 문제 해결",
      "전체적인 QA 담당",
    ],
  },
  {
    id: 5,
    name: "WebtoonNet",
    date: " 2023.12.18 ~ 2024.01.05",
    images: [
      ["/images/HTML.svg", "HTML"],
      ["/images/TypeScript.svg", "TypeScript"],
      ["/images/NextJS-Dark.svg", "NextJS-Dark"],
    ],
    skills: "Next.js, React-query, TypeScript, Zustand,Styled-components",
    github: "https://github.com/CodeJaws/Jawstify",
    deployment: "https://taskify4.vercel.app",
    description: " 개인 및 팀 일정을 함께 관리할 수 있는 반응형 칸반보드 플랫폼",
    accomplishment: [
      "팀 회의 주도 및 의견 조율해 방향성 설명, 팀 멘토와의 소통 및 발표 담당",
      "대시보드/사이드바/초대 페이지 개발 및 무한 스크롤 구현",
      "API 문제 대응 및  다른 팀에게 해결 방안 공유",
      "대표 이미지 셀렉 및 이미지 기반으로 홈 화면 이미지 수정",
      "리팩토링을 통해 React-query 기반 상태 관리로 컴포넌트 간 데이터 연동 문제 해결",
      "전체적인 QA 담당",
    ],
  },
];
