export const PROJECT = [
  {
    id: 1,
    name: "TodayTrip",
    date: "2024.01.20 - 2024.02.26",
    images: [
      ["/images/project/todaytrip/TodayTrip1.png", "TodayTrip1"],
      ["/images/project/todaytrip/TodayTrip2.png", "TodayTrip2"],
      ["/images/project/todaytrip/TodayTrip3.png", "TodayTrip3"],
      ["/images/project/todaytrip/TodayTrip4.png", "TodayTrip4"],
      ["/images/project/todaytrip/TodayTrip5.png", "TodayTrip5"],
    ],
    skills: "Next.js, TypeScript, React-Query, Google Maps API, Axios, Vercel, CSS Modules",
    github: "https://github.com/TripTripNow/TodayTrip",
    deployment: "https://today-trip.vercel.app/",
    description: "체험형 여행 상품을 등록·예약·리뷰할 수 있는  플랫폼",
    accomplishment: [
      "팀 회의 주도 및 의견 조율, 팀 멘토와의 소통 및 발표 담당",
      "체험 등록/수정/관리 페이지 및 알림 모달, NavBar 등 핵심 기능 구현",
      "Google Maps API 담당 및 중복 로딩 이슈 해결",
      "모바일 화면일 경우 UI 위치 사용자 편의성 기반으로 수정",
      "전체적인 QA 및 코드 정리 주도, 프로젝트 오류 빠르게 수정하며 팀 전체 개발 속도 향상",
    ],
  },
  {
    id: 2,
    name: "Jawstify",
    date: "2023.12.18 - 2024.01.05",
    images: [
      ["/images/project/jawstify/Jawstify1.png", "Jawstify1"],
      ["/images/project/jawstify/Jawstify2.png", "Jawstify2"],
      ["/images/project/jawstify/Jawstify3.png", "Jawstify3"],
      ["/images/project/jawstify/Jawstify4.png", "Jawstify4"],
      ["/images/project/jawstify/Jawstify5.png", "Jawstify5"],
    ],
    skills: "Next.js, React-query, TypeScript, Axios, Vercel, Zustand, Styled-components",
    github: "https://github.com/CodeJaws/Jawstify",
    deployment: "https://taskify4.vercel.app",
    description: " 개인 및 팀 일정을 함께 관리할 수 있는 반응형 칸반보드 플랫폼",
    accomplishment: [
      "팀 회의 주도 및 의견 조율, 팀 멘토와의 소통 및 발표 담당",
      "대시보드/사이드바/초대 페이지 개발 및 무한 스크롤 구현",
      "API 문제 대응 및  다른 팀에게 해결 방안 공유",
      "대표 이미지 셀렉 및 이미지 기반으로 홈 화면 이미지 수정",
      "리팩토링을 통해 React-query 기반 상태 관리로 컴포넌트 간 데이터 연동 문제 해결",
      "전체적인 QA 담당",
    ],
  },
  {
    id: 3,
    name: "OpenMind",
    date: "2023.11.08 ~ 2023.11.23",
    images: [
      ["/images/project/openmind/OpenMind1.png", "OpenMind1"],
      ["/images/project/openmind/OpenMind2.png", "OpenMind2"],
      ["/images/project/openmind/OpenMind3.png", "OpenMind3"],
    ],
    skills: "React, Recoil, Styled-components, Axios, Vercel",
    github: "https://github.com/Team-Mind-Open/open-mind",
    deployment: "http://open-mind-nu.vercel.app",
    description: "질문과 답변을 통해 소통하는 감정 공유형 커뮤니케이션 플랫폼",
    accomplishment: [
      "Post/Answer 페이지 전체 구현 및 무한 스크롤 적용",
      "잘못된 접근 시 페이지 깜빡임 문제 해결 → Route 단계에서 에러 분기 처리",
      "에러 처리 모달 디자인, 다크모드 전체적인 색상 셀렉",
      "좋아요/싫어요 버튼 연타 오류 해결을 위해 debounce 적용, API 안정성 확보",
      "전체적인 QA 담당: 로딩 스피너, 잘못된 URL/경로 대응, 빠른 조작·전환 등 다양한 시나리오 테스트",
    ],
  },
  {
    id: 4,
    name: "번역방",
    date: "2025.07.04 - 2025.07.10",
    images: [
      ["/images/project/translationroom/TranslationRoom1.png", "TranslationRoom1"],
      ["/images/project/translationroom/TranslationRoom2.png", "TranslationRoom2"],
      ["/images/project/translationroom/TranslationRoom3.png", "TranslationRoom3"],
      ["/images/project/translationroom/TranslationRoom4.png", "TranslationRoom4"],
      ["/images/project/translationroom/TranslationRoom5.png", "TranslationRoom5"],
      ["/images/project/translationroom/TranslationRoom6.png", "TranslationRoom6"],
      ["/images/project/translationroom/TranslationRoom7.png", "TranslationRoom7"],
      ["/images/project/translationroom/TranslationRoom8.png", "TranslationRoom8"],
    ],
    skills: "React, CSS Modules, react-i18next, Axios, qrcode.react, react-pdf, react-modal",
    github: "https://github.com/zermzerm/translation-room",
    description: "1인 미니프로젝트, 개인 및 팀 일정을 함께 관리할 수 있는 반응형 칸반보드 플랫폼",
    accomplishment: [
      "메인 화면 퍼블리싱 및 검색, 필터링 기능 구현",
      "번역방 생성 모달 구현(react-modal, qrcode.react)",
      "번역방 참여 화면 퍼블리싱 및 기능 구현(react-pdf, react-modal)",
      "다국어 기능 구현(react-i18next)",
      "리팩토링을 통해 React-query 기반 상태 관리로 컴포넌트 간 데이터 연동 문제 해결",
    ],
  },
  {
    id: 5,
    name: "WebtoonNet",
    date: "2025.06.24 - 2025.08.28",
    images: [
      ["/images/project/webtoonnet/WebtoonNet1.png", "WebtoonNet1"],
      ["/images/project/webtoonnet/WebtoonNet2.png", "WebtoonNet2"],
      ["/images/project/webtoonnet/WebtoonNet3.png", "WebtoonNet3"],
      ["/images/project/webtoonnet/WebtoonNet4.png", "WebtoonNet4"],
      ["/images/project/webtoonnet/WebtoonNet5.png", "WebtoonNet5"],
      ["/images/project/webtoonnet/WebtoonNet6.png", "WebtoonNet6"],
      ["/images/project/webtoonnet/WebtoonNet7.png", "WebtoonNet7"],
      ["/images/project/webtoonnet/WebtoonNet8.png", "WebtoonNet8"],
      ["/images/project/webtoonnet/WebtoonNet9.png", "WebtoonNet9"],
      ["/images/project/webtoonnet/WebtoonNet10.png", "WebtoonNet10"],
    ],
    skills: "React, Nextjs, TypeScript, Styled-Components",
    github: "https://github.com/zermzerm/wtn",
    description: "1인 미니프로젝트, App Router 학습을 위해 만들어본 웹툰 리뷰 사이트",
    accomplishment: [
      "전체적인 페이지 퍼블리싱",
      "메인 페이지(swiper, css 애니메이션 학습)",
      "웹툰 랭킹 페이지(App Router [slug] 학습)",
      "웹툰 리뷰 페이지(별점 상세 표시 css만으로 만들기 학습)",
      "웹툰 컬렉션 페이지",
      "웹툰 검색 페이지",
      "커뮤니티 페이지",
      "로그인/회원가입 페이지",
    ],
  },
  {
    id: 6,
    name: "포트폴리오 사이트",
    date: "2025.11.27 - 2025.12.02",
    images: [
      ["/images/project/portfolio/Portfolio1.png", "Portfolio1"],
      ["/images/project/portfolio/Portfolio2.png", "Portfolio2"],
      ["/images/project/portfolio/Portfolio3.png", "Portfolio3"],
      ["/images/project/portfolio/Portfolio4.png", "Portfolio4"],
    ],
    skills: "Nextjs, TypeScript, Tailwind, framer-motion, Vercel",
    github: "https://github.com/zermzerm/wtn",
    deployment: "https://pks-portfolio-v2.vercel.app/",
    description: "1인 미니프로젝트, App Router, Tailwind, framer-motion 학습하기 위해 만든 사이트",
    accomplishment: [
      "전체적인 페이지 퍼블리싱",
      "Styled-components에서 Tailwind로 마이그레이션",
      "framer-motion 전체적으로 적용",
    ],
  },
];
